const express=require('express')
const router=express.Router()
const { perchaseItem,getAllPerchaseItem,deletePerchaseItem,updatePerchaseItem } = require('../../controller/PerchaseOrder/Perchase')
const {requestAppointment, getAppointments, schuduleAppointment} = require('../../controller/Appointment/appointRequest')
router.post('/perchaseOrder', perchaseItem)
router.get('/getAllPerchaseItem', getAllPerchaseItem)
router.delete('/deletePerchaseItem', deletePerchaseItem)
router.put('/updatePerchaseItem', updatePerchaseItem)
router.post('/requestAppointment', requestAppointment)
module.exports = router;